version: '3.9'

networks:
  home-chef-network:

services:
  nginx:
    image: nginx
    container_name: nginx-service
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
      - ./nginx/log/access.log:/var/log/nginx/access.log
    depends_on:
      - php
    networks:
      - home-chef-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-service
    volumes:
      - ./:/var/www/html
    ports:
      - "9011:9000"
    networks:
      - home-chef-network